# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [3]:
import numpy as np

#### Create an array of 10 zeros 

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
5*np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [6]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [7]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [9]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [12]:
np.random.rand()

0.951962806590464

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [10]:
np.random.randn(25)

array([ 0.40031829, -0.73435875,  0.97407553, -0.58086797,  0.25591484,
        1.11811654,  0.01056305, -0.22344749,  0.64894223, -0.42721787,
       -1.16992981, -0.14906157,  2.59672955, -0.29561711,  0.9148382 ,
       -1.62615429,  0.54345064, -0.79133085, -0.13574131,  2.17015627,
        0.040368  , -1.55066839, -0.82266873,  0.34979355, -1.38239397])

#### Create the following matrix:

In [11]:
np.random.random_sample((10,10))

array([[0.84825671, 0.33001697, 0.76749216, 0.59287897, 0.52692298,
        0.13918362, 0.68887491, 0.77034603, 0.69632818, 0.04910924],
       [0.11137996, 0.52799996, 0.42837367, 0.21983692, 0.24172483,
        0.27200768, 0.85358715, 0.19844347, 0.38841379, 0.15274534],
       [0.38419936, 0.36490549, 0.47998566, 0.18614243, 0.77454128,
        0.54799219, 0.56781406, 0.16569539, 0.93429755, 0.25425243],
       [0.27334489, 0.66054252, 0.64007476, 0.10174843, 0.34167355,
        0.74504906, 0.12630249, 0.88280838, 0.45593951, 0.73936693],
       [0.26051218, 0.7351287 , 0.7235287 , 0.71860206, 0.33676076,
        0.93175409, 0.95079273, 0.8534069 , 0.26284868, 0.94600248],
       [0.77118203, 0.93511474, 0.57666535, 0.05436533, 0.95280611,
        0.33649268, 0.44241477, 0.62800669, 0.61152203, 0.79513943],
       [0.75999933, 0.22359466, 0.93022581, 0.97027104, 0.15398365,
        0.42536625, 0.55186188, 0.86615935, 0.74838826, 0.98212437],
       [0.97122267, 0.89889477, 0.1364806

#### Create an array of 20 linearly spaced points between 0 and 1:

In [12]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [14]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [15]:
mat[3,4]

20

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [16]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [29]:
mat[4]

array([21, 22, 23, 24, 25])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [30]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [31]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [32]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [0]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

# Great Job!